#number1=10
#number2=5
#summation=number1+number2
#print("sumation result:",summation)
#subtraction=number1-number2
#print("subtraction result:",subtraction)

#multiplication=number1*number2
#print("multiplication result:", multiplication)

#division=number1/number2
#print("division result:", division )
"""
number1=12
type(number1)
int
number1=10.0
type(number1)
float
name="mr.x"
type(name)
str
age="13"
type(age)
str
number1=12
number2=6.5
result=number1+number2
print(result)
number3="100"
result=numbrt1=number3
print(result)
"""
"""

x=input("type a number:")
y=input("type another number:")
sum=int(x)+int(y)
print("the sum is:",sum)